[workspace]
members = [
    "day1/day1part1",
    "day1/day1part2",
    "day2/day2part1",
    "day2/day2part2",
    "day3/day3part1",
    "day3/day3part2",
    "day4/day4part1",
    "day4/day4part2",
]
resolver = "2"